package org.ecews.renaissance.repositories.projections;

import java.math.BigDecimal;

public record PatientReportProjection(
        Long id,
        Integer age,
        String ageUnit,
        String sex,
        String phoneNumber,
        String maritalStatus,
        String tribe,
        String religion,
        String occupation,
        String address,
        BigDecimal weight,
        BigDecimal height,
        BigDecimal temperature,
        Integer systolicBp,
        Integer diastolicBp,
        Integer pulseRate,
        Integer respiratoryRate,
        BigDecimal bmi,
        String randomBloodSugar,
        String malariaParasiteRdt,
        String hepatitisB,
        String hepatitisC,
        String hivTest,
        String cholesterol,
        String psa,
        String generalDiagnosis,
        String generalTreatments,
        String generalServicesReferred,
        String generalReferred,
        String dentalDiagnoses,
        String dentalOthersDiagnosis,
        String dentalTreatments,
        String dentalOthersTreatment,
        String dentalDispensed,
        String dentalServicesReferred,
        String dentalReferred,
        String eyeDiagnosis,
        String eyeOthersDiagnosis,
        String eyeTreatments,
        String eyeOthersTreatment,
        String eyeSurgery,
        String eyeOtherSurgery,
        String visualAcuityLeft,
        String visualAcuityRight,
        String eyeReferred,
        String glassesDispensed,
        String ancillaryServices,
        String deworming,
        String itn,
        String dentalToothpaste,
        String dentalToothbrush,
        Integer prescriptionCount) {
}
