description: This plugin help in data collection for the renaissance project
name: Renaissance
translations:
  - lang: en
    path: installers/renaissance-plugin/i18n/en.json
  - lang: fr
    path: installers/renaissance-plugin/i18n/fr.json
  - lang: es
    path: installers/renaissance-plugin/i18n/es.json
  - lang: pt
    path: installers/renaissance-plugin/i18n/pt.json
  - lang: yo
    path: installers/renaissance-plugin/i18n/yo.json
  - lang: ig
    path: installers/renaissance-plugin/i18n/ig.json
  - lang: ha
    path: installers/renaissance-plugin/i18n/ha.json
  - lang: sw
    path: installers/renaissance-plugin/i18n/sw.json
configurationsPath: installers/renaissance-plugin/configuration.json
valueSetsPath: installers/renaissance-plugin/value-sets.json
menus:
  - name: Clients
    type: link
    route: clients
    icon: library_books
    authorities:
      - Renaissance
webRemotes:
  - remoteEntry: "/js/renaissance-plugin/remoteEntry.js"
    remoteName: _85fdc14b_9a1d_4480_adff_4f1a98971a0c
    modules:
      - name: TutorialRouting
        routePath: clients
        title: Clients
      - name: ClientDashboardRouting
        routePath: client-dashboard
        title: Client Dashboard
permissions:
  - name: Edit Triage
    group: Renaissance
  - name: Create Triage
    group: Renaissance
  - name: Dispense Drug
    group: Renaissance
  - name: Select Test
    group: Renaissance
  - name: See General Consultation Card
    group: Renaissance
  - name: See Pharmacy Card
    group: Renaissance
  - name: Do Prescription
    group: Renaissance
  - name: See Dental Consultation Card
    group: Renaissance
  - name: See Ancillary Service Card
    group: Renaissance
  - name: Can Open Create Dental Consultation
    group: Renaissance
  - name: Can Open Ancillary Service
    group: Renaissance
  - name: Can Create Client
    group: Renaissance
  - name: Renaissance
    group: Renaissance
  - name: Can See Laboratory Card
    group: Renaissance
  - name: Client Dashboard
    group: Renaissance
  - name: Can See Triage Card
    group: Renaissance
  - name: Enter Test Result
    group: Renaissance
  - name: See Consultation Data
    group: Renaissance
  - name: Dispense ITN
    group: Renaissance
  - name: Can Modify Consultation
    group: Renaissance
  - name: Can Create Consultation
    group: Renaissance
  - name: Can Modify Triage
    group: Renaissance
  - name: Can Modify Client Details
    group: Renaissance
  - name: Can View Client Details Can
    group: Renaissance
  - name: Can Modify Dental Consultation
    group: Renaissance
  - name: See Eye Care Service Card
    group: Renaissance
  - name: Can Open Ophthalmologists Service
    group: Renaissance
  - name: Can Modify Ophthalmologists Service
    group: Renaissance
  - name: Can Edit Lab Result
    group: Renaissance
